### ISSUE TITLE
No matching client found for package name 'com.food.ordering.zinger.debug'

### ISSUE THREAD

**Issue by ayush9090** [shrikanth7698/Zinger-Android-App#2]
![Screenshot (1)](https://user-images.githubusercontent.com/35886894/85685131-60281c80-b6ec-11ea-81ef-02994273a32b.png)

**Comment by shrikanth7698** [comment]
1. Create a firebase project, add this android app i.e add this package name `com.food.ordering.zinger.debug` to that project:
<a href="https://firebase.google.com/docs/android/setup" target="_blank">Firebase setup</a>

![zinger_settings](https://user-images.githubusercontent.com/25195315/85693422-dbd99780-b6f3-11ea-97ed-a28727e5ee08.JPG)

2. Download **google-services.json** from the firebase project you created earlier and add it to the project under **app** folder
